#!/bin/sh
# Fixes the issue the causes SourceTree to not run the pre-commit hook with the error:
# 'env: node: No such file or directory'
PATH=$PATH:/usr/local/bin:/usr/local/sbin

# Test prospective commit
./node_modules/.bin/gulp analyticss
exit 0;
